version: "3.9"

services:
  app:
    container_name: fighting-korea
    image: fighting-korea
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
